- hosts: all

  tasks:

    - name: Run run_tests.sh
      shell:
        chdir: '{{ ansible_user_dir }}/workspace'
        executable: /bin/bash
        cmd: |
          set -e
          set -x
          ./run_tests.sh
