#!/bin/bash
#
# lib/cinder_plugins/bdd
# Configure the BlockDeviceDriver driver

# Enable with:
#
#   CINDER_DRIVER=bdd

# Dependencies:
#
# - ``functions`` file
# - ``cinder`` configurations

# CINDER_CONF
# CINDER_BLOCK_DEVICES

# configure_cinder_driver - make configuration changes, including those to other services

# Save trace setting
MY_XTRACE=$(set +o | grep xtrace)
set +o xtrace

function cleanup_cinder_driver {
    cleanup_cinder_bdd_devices
}


# configure_cinder_driver - Set config files, create data dirs, etc
function configure_cinder_driver {
    iniset $CINDER_CONF DEFAULT volume_driver "cinder.volume.drivers.block_device.BlockDeviceDriver"
    local dev=$(get_cinder_bdd_devices)
    iniset $CINDER_CONF $be_name available_devices $dev
}

# Restore xtrace
$MY_XTRACE

# Local variables:
# mode: shell-script
# End:q
