- nodeset:
    name: openstack-single-node
    nodes:
      - name: controller
        label: ubuntu-xenial
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: devstack-single-node-ubuntu-xenial-arm64
    nodes:
      - name: controller
        label: ubuntu-xenial-arm64
    groups:
      - name: tempest
        nodes:
          - controller

- job:
    name: devstack-base
    parent: multinode
    abstract: true
    description: |
      Base abstract Devstack job.

      Defines plays and base variables, but it does not include any project
      and it does not run any service by default. This is a common base for
      all single Devstack jobs, single or multinode.
      Variables are defined in job.vars, which is what is then used by single
      node jobs and by multi node jobs for the controller, as well as in
      job.group-vars.peers, which is what is used by multi node jobs for peer
      nodes (everything but the controller).
    required-projects:
      - openstack-dev/devstack
    roles:
      - zuul: openstack-infra/devstack-gate
      - zuul: openstack-infra/openstack-zuul-jobs
    vars:
      devstack_localrc:
        DATABASE_PASSWORD: secretdatabase
        RABBIT_PASSWORD: secretrabbit
        ADMIN_PASSWORD: secretadmin
        SERVICE_PASSWORD: secretservice
        NETWORK_GATEWAY: 10.1.0.1
        FIXED_RANGE: 10.1.0.0/20
        IPV4_ADDRS_SAFE_TO_USE: 10.1.0.0/20
        FLOATING_RANGE: 172.24.5.0/24
        PUBLIC_NETWORK_GATEWAY: 172.24.5.1
        LOGFILE: /opt/stack/logs/devstacklog.txt
        LOG_COLOR: false
        VERBOSE: true
        VERBOSE_NO_TIMESTAMP: true
        NOVNC_FROM_PACKAGE: true
        ERROR_ON_CLONE: true
        # Gate jobs can't deal with nested virt. Disable it.
        LIBVIRT_TYPE: qemu
        # NOTE(dims): etcd 3.x is not available in debian/ubuntu
        # etc. As a stop gap measure, devstack uses wget to download
        # from the location below for all the CI jobs.
        ETCD_DOWNLOAD_URL: http://tarballs.openstack.org/etcd/
      devstack_services:
        base: false
      zuul_copy_output:
        '{{ devstack_conf_dir }}/local.conf': 'logs'
        '{{ devstack_conf_dir }}/localrc': 'logs'
        '{{ devstack_conf_dir }}/.localrc.auto': 'logs'
        '{{ devstack_conf_dir }}/.stackenv': 'logs'
        '{{ devstack_log_dir }}/dstat-csv.log': 'logs'
        '{{ devstack_log_dir }}/devstacklog.txt': 'logs'
        '{{ devstack_log_dir }}/devstacklog.txt.summary': 'logs'
        '{{ devstack_full_log}}': 'logs'
        '{{ stage_dir }}/verify_tempest_conf.log': 'logs'
        '{{ stage_dir }}/apache': 'logs'
        '{{ stage_dir }}/apache_config': 'logs'
        '{{ stage_dir }}/etc': 'logs'
        '/var/log/rabbitmq': 'logs'
        '/var/log/postgresql': 'logs'
        '/var/log/mysql.err': 'logs'
        '/var/log/mysql.log': 'logs'
        '/var/log/libvirt': 'logs'
        '/etc/sudoers': 'logs'
        '/etc/sudoers.d': 'logs'
        '{{ stage_dir }}/iptables.txt': 'logs'
        '{{ stage_dir }}/df.txt': 'logs'
        '{{ stage_dir }}/pip2-freeze.txt': 'logs'
        '{{ stage_dir }}/pip3-freeze.txt': 'logs'
        '{{ stage_dir }}/dpkg-l.txt': 'logs'
        '{{ stage_dir }}/rpm-qa.txt': 'logs'
        '{{ stage_dir }}/core': 'logs'
        '{{ stage_dir }}/listen53.txt': 'logs'
        '{{ stage_dir }}/deprecations.log': 'logs'
        '/var/log/ceph': 'logs'
        '/var/log/openvswitch': 'logs'
        '/var/log/glusterfs': 'logs'
        '/etc/glusterfs/glusterd.vol': 'logs'
        '/etc/resolv.conf': 'logs'
        '/var/log/unbound.log': 'logs'
      extensions_to_txt:
        conf: True
        log: True
        localrc: True
        stackenv: True
        auto: True
    group-vars:
      peers:
        devstack_localrc:
          DATABASE_PASSWORD: secretdatabase
          RABBIT_PASSWORD: secretrabbit
          ADMIN_PASSWORD: secretadmin
          SERVICE_PASSWORD: secretservice
          NETWORK_GATEWAY: 10.1.0.1
          FIXED_RANGE: 10.1.0.0/20
          IPV4_ADDRS_SAFE_TO_USE: 10.1.0.0/20
          FLOATING_RANGE: 172.24.5.0/24
          PUBLIC_NETWORK_GATEWAY: 172.24.5.1
          LOGFILE: /opt/stack/logs/devstacklog.txt
          LOG_COLOR: false
          VERBOSE: true
          VERBOSE_NO_TIMESTAMP: true
          NOVNC_FROM_PACKAGE: true
          ERROR_ON_CLONE: true
          LIBVIRT_TYPE: qemu
          ETCD_DOWNLOAD_URL: http://tarballs.openstack.org/etcd/
        devstack_services:
          base: false
    pre-run: playbooks/pre.yaml
    run: playbooks/devstack.yaml
    post-run: playbooks/post.yaml
    irrelevant-files:
      # Documentation related
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
      # Translations
      - ^.*/locale/.*po$

- job:
    name: devstack
    parent: devstack-base
    description: |
      Single node devstack job for integration gate.
    nodeset: openstack-single-node
    required-projects:
      - openstack/cinder
      - openstack/glance
      - openstack/keystone
      - openstack/neutron
      - openstack/nova
      - openstack/requirements
      - openstack/swift
    timeout: 7200
    vars:
      test_matrix_configs: [neutron, tlsproxy]
      devstack_localrc:
        # Common OpenStack services settings
        SWIFT_REPLICAS: 1
        SWIFT_START_ALL_SERVICES: false
        SWIFT_HASH: 1234123412341234
        CINDER_PERIODIC_INTERVAL: 10
        DEBUG_LIBVIRT_COREDUMPS: True
        NOVA_VNC_ENABLED: true
        VNCSERVER_LISTEN: 0.0.0.0
        VNCSERVER_PROXYCLIENT_ADDRESS: "{{ hostvars[inventory_hostname]['nodepool']['private_ipv4'] }}"
      devstack_services:
        base: true
        horizon: false
        tempest: false

# NOTE(ianw) Platform tests have traditionally been non-voting because
# we often have to rush things through devstack to stabilise the gate,
# and these platforms don't have the round-the-clock support to avoid
# becoming blockers in that situation.
- job:
    name: devstack-platform-ubuntu-xenial-arm64
    parent: tempest-full
    description: Ubuntu Xenial ARM64 platform test
    nodeset: devstack-single-node-ubuntu-xenial-arm64
    voting: false

- project:
    check:
      jobs:
        - devstack
        - devstack-platform-ubuntu-xenial-arm64
    gate:
      jobs:
        - devstack
        - devstack-platform-ubuntu-xenial-arm64
