- nodeset:
    name: vexx-bionic
    nodes:
     - name: ubuntu-bionic
       label: ubuntu-bionic-vexxhost

- nodeset:
    name: openstack-single-node
    nodes:
      - name: controller
        label: ubuntu-xenial
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: openstack-single-node-focal
    nodes:
      - name: controller
        label: ubuntu-focal
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: openstack-single-node-bionic
    nodes:
      - name: controller
        label: ubuntu-bionic
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: openstack-single-node-xenial
    nodes:
      - name: controller
        label: ubuntu-xenial
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: devstack-single-node-centos-7
    nodes:
      - name: controller
        label: centos-7
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: devstack-single-node-centos-8
    nodes:
      - name: controller
        label: centos-8
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: devstack-single-node-opensuse-15
    nodes:
      - name: controller
        label: opensuse-15
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: devstack-single-node-fedora-latest
    nodes:
      - name: controller
        label: fedora-32
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: openstack-two-node
    nodes:
      - name: controller
        label: ubuntu-xenial
      - name: compute1
        label: ubuntu-xenial
    groups:
      # Node where tests are executed and test results collected
      - name: tempest
        nodes:
          - controller
      # Nodes running the compute service
      - name: compute
        nodes:
          - controller
          - compute1
      # Nodes that are not the controller
      - name: subnode
        nodes:
          - compute1
      # Switch node for multinode networking setup
      - name: switch
        nodes:
          - controller
      # Peer nodes for multinode networking setup
      - name: peers
        nodes:
          - compute1

- nodeset:
    name: openstack-two-node-focal
    nodes:
      - name: controller
        label: ubuntu-focal
      - name: compute1
        label: ubuntu-focal
    groups:
      # Node where tests are executed and test results collected
      - name: tempest
        nodes:
          - controller
      # Nodes running the compute service
      - name: compute
        nodes:
          - controller
          - compute1
      # Nodes that are not the controller
      - name: subnode
        nodes:
          - compute1
      # Switch node for multinode networking setup
      - name: switch
        nodes:
          - controller
      # Peer nodes for multinode networking setup
      - name: peers
        nodes:
          - compute1

- nodeset:
    name: openstack-two-node-bionic
    nodes:
      - name: controller
        label: ubuntu-bionic
      - name: compute1
        label: ubuntu-bionic
    groups:
      # Node where tests are executed and test results collected
      - name: tempest
        nodes:
          - controller
      # Nodes running the compute service
      - name: compute
        nodes:
          - controller
          - compute1
      # Nodes that are not the controller
      - name: subnode
        nodes:
          - compute1
      # Switch node for multinode networking setup
      - name: switch
        nodes:
          - controller
      # Peer nodes for multinode networking setup
      - name: peers
        nodes:
          - compute1

- nodeset:
    name: openstack-two-node-xenial
    nodes:
      - name: controller
        label: ubuntu-xenial
      - name: compute1
        label: ubuntu-xenial
    groups:
      # Node where tests are executed and test results collected
      - name: tempest
        nodes:
          - controller
      # Nodes running the compute service
      - name: compute
        nodes:
          - controller
          - compute1
      # Nodes that are not the controller
      - name: subnode
        nodes:
          - compute1
      # Switch node for multinode networking setup
      - name: switch
        nodes:
          - controller
      # Peer nodes for multinode networking setup
      - name: peers
        nodes:
          - compute1

- nodeset:
    name: openstack-three-node-focal
    nodes:
      - name: controller
        label: ubuntu-focal
      - name: compute1
        label: ubuntu-focal
      - name: compute2
        label: ubuntu-focal
    groups:
      # Node where tests are executed and test results collected
      - name: tempest
        nodes:
          - controller
      # Nodes running the compute service
      - name: compute
        nodes:
          - controller
          - compute1
          - compute2
      # Nodes that are not the controller
      - name: subnode
        nodes:
          - compute1
          - compute2
      # Switch node for multinode networking setup
      - name: switch
        nodes:
          - controller
      # Peer nodes for multinode networking setup
      - name: peers
        nodes:
          - compute1
          - compute2

- nodeset:
    name: openstack-three-node-bionic
    nodes:
      - name: controller
        label: ubuntu-bionic
      - name: compute1
        label: ubuntu-bionic
      - name: compute2
        label: ubuntu-bionic
    groups:
      # Node where tests are executed and test results collected
      - name: tempest
        nodes:
          - controller
      # Nodes running the compute service
      - name: compute
        nodes:
          - controller
          - compute1
          - compute2
      # Nodes that are not the controller
      - name: subnode
        nodes:
          - compute1
          - compute2
      # Switch node for multinode networking setup
      - name: switch
        nodes:
          - controller
      # Peer nodes for multinode networking setup
      - name: peers
        nodes:
          - compute1
          - compute2

# NOTE(ianw) Platform tests have traditionally been non-voting because
# we often have to rush things through devstack to stabilise the gate,
# and these platforms don't have the round-the-clock support to avoid
# becoming blockers in that situation.
- job:
    name: devstack-platform-centos8-async
    parent: tempest-full-py3
    description: Centos 8 platform test
    nodeset: vexx-centos8
    voting: false
    timeout: 9000
    vars:
      devstack_localrc:
        DEVSTACK_PARALLEL: True

- job:
    name: devstack-platform-async
    parent: tempest-full-py3
    description: Async mode enabled
    voting: false
    nodeset: vexx-bionic
    vars:
      devstack_localrc:
        DEVSTACK_PARALLEL: True

- project:
    templates:
      - integrated-gate-py3
      - publish-openstack-docs-pti
    check:
      jobs:
        - devstack-platform-centos8-async
        - devstack-platform-async
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa:
            voting: false
        - swift-dsvm-functional:
            voting: false
            irrelevant-files: &dsvm-irrelevant-files
              - ^.*\.rst$
              - ^doc/.*$
        - swift-dsvm-functional-py3:
            voting: false
            irrelevant-files: *dsvm-irrelevant-files
        - grenade:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - neutron-grenade-multinode:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - neutron-tempest-linuxbridge:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - neutron-ovn-tempest-ovs-release:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - tempest-multinode-full-py3:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - openstacksdk-functional-devstack:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - tempest-ipv6-only:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - nova-ceph-multistore:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
    gate:
      jobs:
        - neutron-grenade-multinode:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - neutron-tempest-linuxbridge:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - grenade:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - openstacksdk-functional-devstack:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - tempest-ipv6-only:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - nova-ceph-multistore:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
    # Please add a note on each job and conditions for the job not
    # being experimental any more, so we can keep this list somewhat
    # pruned.
    #
    # * nova-next: maintained by nova for unreleased/undefaulted
    #    things
    # * neutron-fullstack-with-uwsgi: maintained by neutron for fullstack test
    #    when neutron-api is served by uwsgi, it's in exprimental for testing.
    #    the next cycle we can remove this  job if things turn out to be
    #    stable enough.
    # * neutron-functional-with-uwsgi: maintained by neutron for functional
    #    test. Next cycle we can remove this one if things turn out to be
    #    stable engouh with uwsgi.
    # * neutron-tempest-with-uwsgi: maintained by neutron for tempest test.
    #    Next cycle we can remove this if everything run out stable enough.
    # * nova-multi-cell: maintained by nova and currently non-voting in the
    #    check queue for nova changes but relies on devstack configuration
    # * devstack-platform-fedora-latest-virt-preview: Maintained by lyarwood
    #    for Nova to allow early testing of the latest versions of Libvirt and
    #    QEMU. Should only graduate out of experimental if it ever moves into
    #    the check queue for Nova.

    experimental:
      jobs:
        - nova-multi-cell
        - nova-next
        - neutron-fullstack-with-uwsgi
        - neutron-functional-with-uwsgi
        - neutron-tempest-with-uwsgi
        - devstack-plugin-ceph-tempest-py3:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - neutron-tempest-dvr:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - neutron-tempest-dvr-ha-multinode-full:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - cinder-tempest-lvm-multibackend:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - tempest-pg-full:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
        - devstack-platform-fedora-latest-virt-preview
