- name: Generate minimial ceph.conf on controller for subnode
  become: true
  command: |
    ceph config generate-minimal-conf > /etc/ceph/client.conf
  when: inventory_hostname == 'controller'

- name: Ensure /etc/ceph exists on the subnode
  become: true
  file:
    path: /etc/ceph
    state: directory
  when: 'inventory_hostname in groups["subnode"]|default([])'

- name: Copy client.conf and ceph.clent.admin.keyring to subnode
  become: true
  synchronize:
    src: "{{ item }}"
    dest: "{{ item }}"
    mode: push
  with_items:
    - "/etc/ceph/client.conf"
    - "/etc/ceph/ceph.clent.admin.keyring"
    - "/etc/ceph/ceph.client.cinder.keyring"
    - "/etc/ceph/ceph.client.glance.keyring" 
  when: 'inventory_hostname in groups["subnode"]|default([])'

- name: Rename client.conf to ceph.conf
  become: true
  command: |
    mv /etc/ceph/client.conf /etc/ceph/ceph.conf
  when: 'inventory_hostname in groups["subnode"]|default([])'
