- name: Generate minimial ceph.conf on controller for subnode
  become: true
  shell: /usr/bin/ceph config generate-minimal-conf > /etc/ceph/client.conf
  args:
    creates: /etc/ceph/client.conf
  when: inventory_hostname == 'controller'

- name: Pull client.conf and keyrings from controller
  become: true
  synchronize:
    src: "{{ item }}"
    dest: "{{ zuul.executor.work_root }}/{{ item | basename }}"
    mode: pull
  with_items:
    - "/etc/ceph/client.conf"
    - "/etc/ceph/ceph.clent.admin.keyring"
    - "/etc/ceph/ceph.client.cinder.keyring"
    - "/etc/ceph/ceph.client.glance.keyring"
  when: inventory_hostname == 'controller'

- name: Ensure /etc/ceph exists on the subnode
  become: true
  file:
    path: /etc/ceph
    state: directory
  when: 'inventory_hostname in groups["subnode"]|default([])'

- name: Push client.conf to subnode as /etc/ceph/ceph.conf
  become: true
  synchronize:
    src: "{{ zuul.executor.work_root }}/client.conf"
    dest: "/etc/ceph/ceph.conf"
    mode: push
  when: 'inventory_hostname in groups["subnode"]|default([])'

- name: Push keyrings to subnode
  become: true
  synchronize:
    src: "{{ zuul.executor.work_root }}/{{ item | basename }}"
    dest: "/etc/ceph/{{ item | basename }}"
    mode: push
  with_items:
    - "/etc/ceph/ceph.clent.admin.keyring"
    - "/etc/ceph/ceph.client.cinder.keyring"
    - "/etc/ceph/ceph.client.glance.keyring" 
  when: 'inventory_hostname in groups["subnode"]|default([])'
