- hosts: all
  roles:
    - run-devstack
    - get-devstack-os-environment
    # Run bindep and test-setup after devstack so that they won't interfere
    - role: bindep
      bindep_profile: test
      bindep_dir: "{{ zuul_work_dir }}"
    - test-setup
    - ensure-tox
    - role: tox
      tox_environment: "{{ os_env_var|default({}) }}"
