- name: Generate statistics
  shell:
    executable: /bin/bash
    cmd: |
      source {{ devstack_conf_dir }}/stackrc
      python3 {{ devstack_conf_dir }}/tools/get-stats.py \
        --db-user="$DATABASE_USER" \
        --db-pass="$DATABASE_PASSWORD" \
        --db-host="$DATABASE_HOST" \
        {{ apache_logs }} > {{ stage_dir }}/performance.json
      mysqldump -u $DATABASE_USER -p$DATABASE_PASSWORD performance_schema | gzip > {{ stage_dir }}/performance_schema.sql.gz
  vars:
    apache_logs: >-
      {% for i in debian_suse_apache_deref_logs.results | default([]) + redhat_apache_deref_logs.results | default([]) %}
      --apache-log="{{ i.stat.path }}"
      {% endfor %}

- name: Check if static performance file exists
  stat:
    path: "{{ devstack_conf_dir }}/perfdata/{{ zuul.project.short_name }}/{{ zuul.job }}.json"
  register: static_perf_file

- name: Report on performance data
  shell:
    executable: /bin/bash
    cmd: |
      python3 {{ devstack_conf_dir }}/tools/grok_performance.py \
        {{ static_perf_file.stat.path }} {{ stage_dir }}/performance.json
  when: static_perf_file.stat.exists
