- name: Ensure the data folder exists
  become: true
  file:
    path: "{{ devstack_base_dir }}/data"
    state: directory
    owner: stack
    group: stack
    mode: 0755
  when: inventory_hostname in groups['subnode']

- name: Ensure the CA folder exists
  become: true
  file:
    path: "{{ devstack_base_dir }}/data/CA"
    state: directory
    owner: stack
    group: stack
    mode: 0755
  when: inventory_hostname in groups['subnode']

- name: Pull the CA certificate and folder
  become: true
  synchronize:
    src: "{{ item }}"
    dest: "{{ zuul.executor.work_root }}/{{ item | basename }}"
    mode: pull
  with_items:
    - "{{ devstack_base_dir }}/data/ca-bundle.pem"
    - "{{ devstack_base_dir }}/data/CA"
  when: inventory_hostname == 'controller'

- name: Push the CA certificate and folder
  become: true
  become_user: stack
  synchronize:
    src: "{{ zuul.executor.work_root }}/{{ item }}"
    dest: "{{ devstack_base_dir }}/data/{{ item }}"
    mode: pull
  with_items:
    - ca-bundle.pem
    - CA
  when: inventory_hostname in groups['subnode']
