---
- name: Create /home/stack/bin
  file:
    path: /home/stack/bin
    state: directory
    owner: stack
    group: stack
  become: yes
- name: Copy OSC service client
  copy:
    src: openstack
    dest: /home/stack/bin/openstack
    owner: stack
    group: stack
    mode: '775'
  become: yes
- name: Copy OSC service server
  copy:
    src: openstack-cli-server
    dest: /home/stack/bin/openstack-cli-server
    owner: stack
    group: stack
    mode: '775'
  become: yes
- name: Pip install openstackclient
  pip:
    name: python-openstackclient
  become: yes
- name: Copy openstack-cli-server service file
  copy:
    src: openstack-cli-server.service
    dest: /etc/systemd/system
  become: yes
- name: Systemd daemon-reload
  command: systemctl daemon-reload
  become: yes
- name: Start openstack-cli-server
  service:
    name: openstack-cli-server
    state: started
  become: yes
