# Setup the controller first and pushes the CA data to subnodes
# NOTE(andreaf) In future we may want to have a way to setup the CA on ansible
# side an push it to all nodes so that they may run in parallel (as long as
# other orchestration issues are solved).
- hosts: controller
  roles:
    - run-devstack

# Run non controller setup after controller is up. This is necessary
# because services like nova apparently expect to have the controller in
# place before anything else.
- hosts: subnode
  roles:
    - sync-devstack-data
    - run-devstack
