- hosts: all
  # This is the default strategy, however since orchestrate-devstack requires
  # "linear", it safer to enforce it in case this is running in an environment
  # configured with a different default strategy.
  strategy: linear
  roles:
    - orchestrate-devstack
