- hosts: all
  become: True
  vars:
    devstack_conf_dir: "{{ devstack_base_dir|default('/opt/stack') }}/devstack/"
    stage_dir: "{{ devstack_base_dir|default('/opt/stack') }}"
  roles:
    - export-devstack-journal
    - apache-logs-conf
    - role: stage-output
      zuul_copy_output:
        { '{{ devstack_conf_dir }}/local.conf': 'logs',
          '{{ devstack_conf_dir }}/.stackenv': 'logs',
          '{{ stage_dir }}/apache': 'logs',
          '{{ stage_dir }}/apache_config': 'logs',
          '/var/log/rabbitmq': 'logs',
          '/var/log/postgresql': 'logs',
          '/var/log/mysql.err': 'logs',
          '/var/log/mysql.log': 'logs' }
      extensions_to_txt:
        - conf
        - log
    - fetch-devstack-log-dir
