- hosts: all
  become: True
  vars:
    devstack_conf_dir: "{{ devstack_base_dir|default('/opt/stack') }}/devstack/"
  roles:
    - export-devstack-journal
    - apache-logs-conf
    - role: stage-output
      zuul_copy_output:
        { '{{ devstack_conf_dir }}/local.conf': 'logs',
          '{{ devstack_conf_dir }}/.stackenv': 'logs',
          '{{ stage_dir }}/apache': 'logs',
          '{{ stage_dir }}/apache_config': 'logs',
          '/var/log/rabbitmq': 'logs',
          '/var/log/postgresql': 'logs',
          '/var/log/mysql.err': 'logs',
<<<<<<< HEAD
          '/var/log/mysql.log': 'logs' }
=======
          '/var/log/mysql.log': 'logs',
          '/var/log/libvirt': 'logs',
          '/etc/sudoers': 'logs',
          '/etc/sudoers.d': 'logs'}
>>>>>>> b4f8d458... Stage libvirt logs and sudoers
      extensions_to_txt:
        - conf
        - log
    # NOTE(andreaf) We need fetch-devstack-log-dir only as long as the base job
    # starts pulling logs for us from {{ ansible_user_dir }}/logs.
    # Meanwhile we already store things in ansible_user_dir and use
    # fetch-devstack-log-dir setting devstack_base_dir
    - role: fetch-devstack-log-dir
      devstack_base_dir: "{{ ansible_user_dir }}"
