- hosts: all
  become: True
  vars:
    devstack_log_dir: "{{ devstack_base_dir|default('/opt/stack') }}/logs/"
    devstack_conf_dir: "{{ devstack_base_dir|default('/opt/stack') }}/devstack/"
  roles:
    - export-devstack-journal
    - role: stage-output
      zuul_copy_output:
        { '{{ devstack_conf_dir }}/local.conf': 'logs',
          '{{ devstack_conf_dir }}/.stackenv': 'logs' ,
          '{{ devstack_log_dir }}/dstat-csv.log': 'logs',
          '{{ devstack_log_dir }}/devstacklog.txt': 'logs',
          '{{ devstack_log_dir }}/devstacklog.txt.summary': 'logs' }
      extensions_to_txt:
        - conf
        - log
        - summary
    # NOTE(andreaf) We need fetch-devstack-log-dir only as long as the base job
    # starts pulling logs for us from {{ ansible_user_dir }}/logs.
    # Meanwhile we already store things in ansible_user_dir and use
    # fetch-devstack-log-dir setting devstack_base_dir
    - role: fetch-devstack-log-dir
      devstack_base_dir: "{{ ansible_user_dir }}"
