- hosts: all
  become: True
  vars:
    devstack_conf_dir: "{{ devstack_base_dir|default('/opt/stack') }}/devstack/"
    stage_dir: "{{ devstack_base_dir|default('/opt/stack') }}"
  roles:
    - export-devstack-journal
    - role: stage-output
      zuul_copy_output:
        { '{{ devstack_conf_dir }}/local.conf': 'logs',
          '{{ devstack_conf_dir }}/.stackenv': 'logs' }
      extensions_to_txt:
        - conf
    - fetch-devstack-log-dir
