- name: Run devstack
  shell:
    cmd: |
      {% if eatmydata %}
      apt install -y eatmydata
      export LD_PRELOAD=libeatmydata.so
      {% endif %}
      ./stack.sh 2>&1
      rc=$?
      echo "*** FINISHED ***"
      exit $rc
  args:
    chdir: "{{devstack_base_dir}}/devstack"
  become: true
  become_user: stack
