- name: Run devstack
  shell:
    cmd: |
      {% if eatmydata %}
      sudo apt install -y eatmydata
      export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libeatmydata.so
      {% endif %}
      ./stack.sh 2>&1
      rc=$?
      echo "*** FINISHED ***"
      exit $rc
  args:
    chdir: "{{devstack_base_dir}}/devstack"
  become: true
  become_user: stack
