- name: Remove /etc/pip.conf configuration
  become: yes
  file:
    dest: /etc/pip.conf
    state: absent

- name: Run devstack
  shell:
    cmd: |
      ./stack.sh 2>&1
      rc=$?
      echo "*** FINISHED ***"
      exit $rc
  args:
    chdir: "{{devstack_base_dir}}/devstack"
  become: true
  become_user: stack
