- name: Write local.conf
  import_role:
    name: write-devstack-local-conf

- name: Run devstack
  shell:
    cmd: |
      ./stack.sh 2>&1
      rc=$?
      echo "*** FINISHED ***"
      exit $rc
  args:
    chdir: "{{devstack_base_dir}}/devstack"
  become: true
  become_user: stack
