- name: Run devstack
  shell:
    cmd: |
      export PATH=/home/stack/bin:$PATH
      ./stack.sh 2>&1
      rc=$?
      echo "*** FINISHED ***"
      exit $rc
  args:
    chdir: "{{devstack_base_dir}}/devstack"
  become: true
  become_user: stack
