# NOTE(ianw): Do this at the very last moment (rather than in
# playbooks/pre.yaml) so that more flags can be added via
# devstack_localrc_extra
- name: Write devstack local conf
  include_role:
    name: write-devstack-local-conf

- name: Run devstack
  shell:
    cmd: |
      ./stack.sh 2>&1
      rc=$?
      echo "*** FINISHED ***"
      exit $rc
  args:
    chdir: "{{devstack_base_dir}}/devstack"
  become: true
  become_user: stack
