- name: Run devstack
  shell:
    cmd: |
      if [ "{{ devstack_openstack_service|default('false') }}" != "false" ]; then
          export PATH=/home/stack/bin:$PATH
      fi
      ./stack.sh 2>&1
      rc=$?
      echo "*** FINISHED ***"
      exit $rc
  args:
    chdir: "{{devstack_base_dir}}/devstack"
  become: true
  become_user: stack
